/*=============================================================================
This file was generated by the AVT VimbaClassGenerator
=============================================================================*/

#ifndef GOLDEYECAMERA_H
#define GOLDEYECAMERA_H

#include "VimbaCPP/Include/VimbaCPP.h"

class GoldeyeCamera : public AVT::VmbAPI::Camera
{
    public:
        typedef SP_DECL( GoldeyeCamera ) Ptr;

        typedef enum _AcquisitionModeEnum
        {
            AcquisitionMode_Continuous = 0,
            AcquisitionMode_SingleFrame = 1,
            AcquisitionMode_MultiFrame = 2
        } AcquisitionModeEnum;

        typedef enum _BPC_OperationModeEnum
        {
            BPC_OperationMode_Deactivated = 0,
            BPC_OperationMode_Activated = 1,
            BPC_OperationMode_Test = 2
        } BPC_OperationModeEnum;

        typedef enum _CounterDecrementEventSourceEnum
        {
            CounterDecrementEventSource_Off = 0,
            CounterDecrementEventSource_PLC_Q16_RisingEdge = 1,
            CounterDecrementEventSource_PLC_Q16_FallingEdge = 2,
            CounterDecrementEventSource_PLC_Q16_AnyEdge = 3,
            CounterDecrementEventSource_PLC_Q16_LevelHigh = 4,
            CounterDecrementEventSource_PLC_Q16_LevelLow = 5
        } CounterDecrementEventSourceEnum;

        typedef enum _CounterResetActivationEnum
        {
            CounterResetActivation_Off = 0,
            CounterResetActivation_RisingEdge = 1,
            CounterResetActivation_FallingEdge = 2,
            CounterResetActivation_AnyEdge = 3,
            CounterResetActivation_LevelHigh = 4,
            CounterResetActivation_LevelLow = 5
        } CounterResetActivationEnum;

        typedef enum _CounterResetSourceEnum
        {
            CounterResetSource_PLC_Q3 = 0,
            CounterResetSource_PLC_Q7 = 1,
            CounterResetSource_PLC_Q8 = 2,
            CounterResetSource_PLC_Q9 = 3,
            CounterResetSource_PLC_Q10 = 4,
            CounterResetSource_PLC_Q11 = 5,
            CounterResetSource_PLC_Q16 = 6,
            CounterResetSource_PLC_Q17 = 7
        } CounterResetSourceEnum;

        typedef enum _DeviceScanTypeEnum
        {
            DeviceScanType_Areascan = 0
        } DeviceScanTypeEnum;

        typedef enum _EventNotificationEnum
        {
            EventNotification_Off = 0,
            EventNotification_On = 1,
            EventNotification_GigEVisionEvent = 3
        } EventNotificationEnum;

        typedef enum _EventSelectorEnum
        {
            EventSelector_DataOverrun = 1,
            EventSelector_Error = 2,
            EventSelector_PLC_Interrupt_FIFO0_Q15 = 3,
            EventSelector_PLC_Interrupt_FIFO0_Q3 = 4,
            EventSelector_PLC_Interrupt_FIFO0_Q7 = 5,
            EventSelector_PLC_Interrupt_FIFO0_Q10 = 6,
            EventSelector_IPEngineCamHeadSerialComLog = 7,
            EventSelector_BlockDiscard = 8
        } EventSelectorEnum;

        typedef enum _ExposureModeEnum
        {
            ExposureMode_Off = 0,
            ExposureMode_Timed = 1
        } ExposureModeEnum;

        typedef enum _GVSPDriverEnum
        {
            GVSPDriver_Socket = 0,
            GVSPDriver_Filter = 1
        } GVSPDriverEnum;

        typedef enum _GevCCPEnum
        {
            GevCCP_OpenAccess = 0,
            GevCCP_ExclusiveAccess = 1,
            GevCCP_ControlAccess = 2
        } GevCCPEnum;

        typedef enum _GevDeviceClassEnum
        {
            GevDeviceClass_Transmitter = 0,
            GevDeviceClass_Receiver = 1,
            GevDeviceClass_Transceiver = 2,
            GevDeviceClass_Peripheral = 3
        } GevDeviceClassEnum;

        typedef enum _GevDeviceModeCharacterSetEnum
        {
            GevDeviceModeCharacterSet_UTF8 = 1
        } GevDeviceModeCharacterSetEnum;

        typedef enum _GevIPConfigurationModeEnum
        {
            GevIPConfigurationMode_LLA = 4,
            GevIPConfigurationMode_Persistent = 5,
            GevIPConfigurationMode_DHCP = 6
        } GevIPConfigurationModeEnum;

        typedef enum _GevIPConfigurationStatusEnum
        {
            GevIPConfigurationStatus_None = 0,
            GevIPConfigurationStatus_PersistentIP = 1,
            GevIPConfigurationStatus_DHCP = 2,
            GevIPConfigurationStatus_LLA = 3,
            GevIPConfigurationStatus_ForceIP = 4
        } GevIPConfigurationStatusEnum;

        typedef enum _GevSCPDirectionEnum
        {
            GevSCPDirection_Transmitter = 0,
            GevSCPDirection_Receiver = 1
        } GevSCPDirectionEnum;

        typedef enum _GevSupportedOptionSelectorEnum
        {
            GevSupportedOptionSelector_IPConfigurationLLA = 0,
            GevSupportedOptionSelector_IPConfigurationDHCP = 1,
            GevSupportedOptionSelector_IPConfigurationPersistentIP = 2,
            GevSupportedOptionSelector_StreamChannelSourceSocket = 3,
            GevSupportedOptionSelector_MessageChannelSourceSocket = 4,
            GevSupportedOptionSelector_CommandsConcatenation = 5,
            GevSupportedOptionSelector_WriteMem = 6,
            GevSupportedOptionSelector_PacketResend = 7,
            GevSupportedOptionSelector_Event = 8,
            GevSupportedOptionSelector_EventData = 9,
            GevSupportedOptionSelector_PendingAck = 10,
            GevSupportedOptionSelector_Action = 11,
            GevSupportedOptionSelector_PrimaryApplicationSwitchover = 12,
            GevSupportedOptionSelector_ExtendedStatusCodes = 13,
            GevSupportedOptionSelector_DiscoveryAckDelay = 14,
            GevSupportedOptionSelector_DiscoveryAckDelayWritable = 15,
            GevSupportedOptionSelector_TestData = 16,
            GevSupportedOptionSelector_ManifestTable = 17,
            GevSupportedOptionSelector_CCPApplicationSocket = 18,
            GevSupportedOptionSelector_LinkSpeed = 19,
            GevSupportedOptionSelector_HeartbeatDisable = 20,
            GevSupportedOptionSelector_SerialNumber = 21,
            GevSupportedOptionSelector_UserDefinedName = 22,
            GevSupportedOptionSelector_StreamChannel0BigAndLittleEndian = 23,
            GevSupportedOptionSelector_StreamChannel0IPReassembly = 24,
            GevSupportedOptionSelector_StreamChannel0UnconditionalStreaming = 25,
            GevSupportedOptionSelector_StreamChannel0ExtendedChunkData = 26
        } GevSupportedOptionSelectorEnum;

        typedef enum _GevTimestampCounterSelectorEnum
        {
            GevTimestampCounterSelector_GevTimestamp = 0,
            GevTimestampCounterSelector_Counter1 = 1
        } GevTimestampCounterSelectorEnum;

        typedef enum _GevTimestampResetActivationEnum
        {
            GevTimestampResetActivation_Disabled = 0,
            GevTimestampResetActivation_RisingEdgeInputSignal = 2
        } GevTimestampResetActivationEnum;

        typedef enum _GevTimestampResetSourceEnum
        {
            GevTimestampResetSource_PLC_Q3 = 0,
            GevTimestampResetSource_PLC_Q7 = 1,
            GevTimestampResetSource_PLC_Q8 = 2,
            GevTimestampResetSource_PLC_Q9 = 3,
            GevTimestampResetSource_PLC_Q10 = 4,
            GevTimestampResetSource_PLC_Q11 = 5,
            GevTimestampResetSource_PLC_Q16 = 6,
            GevTimestampResetSource_PLC_Q17 = 7
        } GevTimestampResetSourceEnum;

        typedef enum _GevTimestampSetActivationEnum
        {
            GevTimestampSetActivation_Disabled = 0,
            GevTimestampSetActivation_RisingEdgeInputSignal = 2
        } GevTimestampSetActivationEnum;

        typedef enum _GevTimestampSetSourceEnum
        {
            GevTimestampSetSource_PLC_Q3 = 0,
            GevTimestampSetSource_PLC_Q7 = 1,
            GevTimestampSetSource_PLC_Q8 = 2,
            GevTimestampSetSource_PLC_Q9 = 3,
            GevTimestampSetSource_PLC_Q10 = 4,
            GevTimestampSetSource_PLC_Q11 = 5,
            GevTimestampSetSource_PLC_Q16 = 6,
            GevTimestampSetSource_PLC_Q17 = 7
        } GevTimestampSetSourceEnum;

        typedef enum _GrbCh0AcqCfgMemoryWaterLevelEnum
        {
            GrbCh0AcqCfgMemoryWaterLevel_Level50 = 0,
            GrbCh0AcqCfgMemoryWaterLevel_Level75 = 1,
            GrbCh0AcqCfgMemoryWaterLevel_Level87Point5 = 2,
            GrbCh0AcqCfgMemoryWaterLevel_Level100 = 3
        } GrbCh0AcqCfgMemoryWaterLevelEnum;

        typedef enum _GrbCh0AcqCfgPixelBusDataPortMappingEnum
        {
            GrbCh0AcqCfgPixelBusDataPortMapping_CBA = 0,
            GrbCh0AcqCfgPixelBusDataPortMapping_CAB = 1,
            GrbCh0AcqCfgPixelBusDataPortMapping_BCA = 2,
            GrbCh0AcqCfgPixelBusDataPortMapping_BAC = 3,
            GrbCh0AcqCfgPixelBusDataPortMapping_ACB = 4,
            GrbCh0AcqCfgPixelBusDataPortMapping_ABC = 5
        } GrbCh0AcqCfgPixelBusDataPortMappingEnum;

        typedef enum _GrbCh0MetadataInsertionModeEnum
        {
            GrbCh0MetadataInsertionMode_FirstFourBytesOfFirstAcquiredLine = 0,
            GrbCh0MetadataInsertionMode_FirstFourBytesOfEveryAcquiredLines = 1
        } GrbCh0MetadataInsertionModeEnum;

        typedef enum _GrbCh0MetadataMsbOverrideEnum
        {
            GrbCh0MetadataMsbOverride_NotOverriden = 0,
            GrbCh0MetadataMsbOverride_PLC_Q0ToPLC_Q7 = 1
        } GrbCh0MetadataMsbOverrideEnum;

        typedef enum _GrbCh0MetadataSourceSelectionEnum
        {
            GrbCh0MetadataSourceSelection_BlockID = 0,
            GrbCh0MetadataSourceSelection_GevTimestampValueLow = 1
        } GrbCh0MetadataSourceSelectionEnum;

        typedef enum _GrbCh0TrigCfgContinuousPipeCountEnum
        {
            GrbCh0TrigCfgContinuousPipeCount_Continuous = 0,
            GrbCh0TrigCfgContinuousPipeCount_One = 1,
            GrbCh0TrigCfgContinuousPipeCount_Two = 2
        } GrbCh0TrigCfgContinuousPipeCountEnum;

        typedef enum _LUT_OperationModeEnum
        {
            LUT_OperationMode_Deactivated = 0,
            LUT_OperationMode_Activated = 1,
            LUT_OperationMode_Test = 2
        } LUT_OperationModeEnum;

        typedef enum _PixelCodingEnum
        {
            PixelCoding_Mono = 0,
            PixelCoding_MonoSigned = 1,
            PixelCoding_MonoPacked = 2,
            PixelCoding_RGBPacked = 3,
            PixelCoding_BGRPacked = 4,
            PixelCoding_RGBAPacked = 5,
            PixelCoding_BGRAPacked = 6,
            PixelCoding_RGBPlanar = 7,
            PixelCoding_YUV411Packed = 8,
            PixelCoding_YUV422Packed = 9,
            PixelCoding_YUV444Packed = 10,
            PixelCoding_YUYVPacked = 11,
            PixelCoding_Raw = 12,
            PixelCoding_RawPacked = 13
        } PixelCodingEnum;

        typedef enum _PixelColorFilterEnum
        {
            PixelColorFilter_None = 0,
            PixelColorFilter_BayerRG = 1,
            PixelColorFilter_BayerGB = 2,
            PixelColorFilter_BayerGR = 3,
            PixelColorFilter_BayerBG = 4
        } PixelColorFilterEnum;

        typedef enum _PixelFormatEnum
        {
            PixelFormat_Mono12 = 17825797
        } PixelFormatEnum;

        typedef enum _PixelSizeEnum
        {
            PixelSize_Bpp8 = 0,
            PixelSize_Bpp10 = 1,
            PixelSize_Bpp12 = 2,
            PixelSize_Bpp14 = 3,
            PixelSize_Bpp16 = 4,
            PixelSize_Bpp24 = 5,
            PixelSize_Bpp32 = 6,
            PixelSize_Bpp36 = 7,
            PixelSize_Bpp48 = 8,
            PixelSize_Bpp64 = 9
        } PixelSizeEnum;

        typedef enum _StreamBufferHandlingModeEnum
        {
            StreamBufferHandlingMode_Default = 0
        } StreamBufferHandlingModeEnum;

        typedef enum _StreamTypeEnum
        {
            StreamType_GEV = 2
        } StreamTypeEnum;

        typedef enum _TPC_OperationModeEnum
        {
            TPC_OperationMode_Deactivated = 0,
            TPC_OperationMode_Activated = 1,
            TPC_OperationMode_Deactivated_Test_A = 2,
            TPC_OperationMode_Deactivated_Test_B = 3,
            TPC_OperationMode_OnePointCorrection_Mode_A = 4,
            TPC_OperationMode_OnePointCorrection_Mode_B = 5
        } TPC_OperationModeEnum;

        typedef enum _TestImageSelectorEnum
        {
            TestImageSelector_Off = 0,
            TestImageSelector_IPEngineTestPattern = 2147483648
        } TestImageSelectorEnum;

        typedef enum _TimerSelectorEnum
        {
            TimerSelector_Timer1 = 0,
            TimerSelector_Timer2 = 1,
            TimerSelector_Timer3 = 2,
            TimerSelector_Timer4 = 3
        } TimerSelectorEnum;

        typedef enum _TimerTriggerActivationEnum
        {
            TimerTriggerActivation_RisingEdge = 0,
            TimerTriggerActivation_LevelHigh = 1,
            TimerTriggerActivation_FallingEdge = 2,
            TimerTriggerActivation_AnyEdge = 3,
            TimerTriggerActivation_LevelLow = 4
        } TimerTriggerActivationEnum;

        typedef enum _TimerTriggerSourceEnum
        {
            TimerTriggerSource_PLC_Q = 0,
            TimerTriggerSource_Continuous = 1
        } TimerTriggerSourceEnum;

        typedef enum _TriggerModeEnum
        {
            TriggerMode_Off = 0,
            TriggerMode_On = 1
        } TriggerModeEnum;

        typedef enum _TriggerSelectorEnum
        {
            TriggerSelector_ExposureActive = 9
        } TriggerSelectorEnum;

        typedef enum _Uart0BaudRateEnum
        {
            Uart0BaudRate_Baud9600 = 0,
            Uart0BaudRate_Baud14400 = 1,
            Uart0BaudRate_Baud19200 = 2,
            Uart0BaudRate_Baud28800 = 3,
            Uart0BaudRate_Baud38400 = 4,
            Uart0BaudRate_Baud57600 = 5,
            Uart0BaudRate_Baud115200 = 6,
            Uart0BaudRate_Programmable = 7
        } Uart0BaudRateEnum;

        typedef enum _Uart0NumOfStopBitsEnum
        {
            Uart0NumOfStopBits_One = 0,
            Uart0NumOfStopBits_Two = 2
        } Uart0NumOfStopBitsEnum;

        typedef enum _Uart0ParityEnum
        {
            Uart0Parity_None = 0,
            Uart0Parity_Even = 1,
            Uart0Parity_Odd = 3
        } Uart0ParityEnum;

        typedef enum _Uart1BaudRateEnum
        {
            Uart1BaudRate_Baud9600 = 0,
            Uart1BaudRate_Baud14400 = 1,
            Uart1BaudRate_Baud19200 = 2,
            Uart1BaudRate_Baud28800 = 3,
            Uart1BaudRate_Baud38400 = 4,
            Uart1BaudRate_Baud57600 = 5,
            Uart1BaudRate_Baud115200 = 6,
            Uart1BaudRate_Programmable = 7
        } Uart1BaudRateEnum;

        typedef enum _Uart1NumOfStopBitsEnum
        {
            Uart1NumOfStopBits_One = 0,
            Uart1NumOfStopBits_Two = 2
        } Uart1NumOfStopBitsEnum;

        typedef enum _Uart1ParityEnum
        {
            Uart1Parity_None = 0,
            Uart1Parity_Even = 1,
            Uart1Parity_Odd = 3
        } Uart1ParityEnum;

        
        GoldeyeCamera (
            const char         *pCameraID,
            const char         *pCameraName,
            const char         *pCameraModel,
            const char         *pCameraSerialNumber,
            const char         *pInterfaceID,
            VmbInterfaceType    interfaceType,
            const char         *pInterfaceName,
            const char         *pInterfaceSerialNumber,
            VmbAccessModeType   interfacePermittedAccess );


        // Category /AcquisitionControl
        VmbErrorType GetTriggerSelector (TriggerSelectorEnum & value);
        VmbErrorType SetTriggerSelector (TriggerSelectorEnum value);
        VmbErrorType GetTriggerSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerMode (TriggerModeEnum & value);
        VmbErrorType SetTriggerMode (TriggerModeEnum value);
        VmbErrorType GetTriggerModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStartExposureTimer (bool & value);
        VmbErrorType SetStartExposureTimer (bool value);
        VmbErrorType GetStartExposureTimerFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTime_Min (VmbInt64_t & value);
        VmbErrorType GetExposureTime_MinFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTime_Max (VmbInt64_t & value);
        VmbErrorType GetExposureTime_MaxFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTimeGranularity (VmbInt64_t & value);
        VmbErrorType SetExposureTimeGranularity (VmbInt64_t value);
        VmbErrorType GetExposureTimeGranularityFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTimeAbsMs (VmbInt64_t & value);
        VmbErrorType SetExposureTimeAbsMs (VmbInt64_t value);
        VmbErrorType GetExposureTimeAbsMsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTimeAbs (double & value);
        VmbErrorType SetExposureTimeAbs (double value);
        VmbErrorType GetExposureTimeAbsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTime (double & value);
        VmbErrorType SetExposureTime (double value);
        VmbErrorType GetExposureTimeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureMode (ExposureModeEnum & value);
        VmbErrorType SetExposureMode (ExposureModeEnum value);
        VmbErrorType GetExposureModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTime_Min (VmbInt64_t & value);
        VmbErrorType GetDarkTime_MinFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTime_Max (VmbInt64_t & value);
        VmbErrorType GetDarkTime_MaxFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTimeGranularity (VmbInt64_t & value);
        VmbErrorType SetDarkTimeGranularity (VmbInt64_t value);
        VmbErrorType GetDarkTimeGranularityFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTimeAbsMs (VmbInt64_t & value);
        VmbErrorType SetDarkTimeAbsMs (VmbInt64_t value);
        VmbErrorType GetDarkTimeAbsMsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTimeAbs (double & value);
        VmbErrorType SetDarkTimeAbs (double value);
        VmbErrorType GetDarkTimeAbsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDarkTime (double & value);
        VmbErrorType SetDarkTime (double value);
        VmbErrorType GetDarkTimeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType AcquisitionStop ();
        VmbErrorType GetAcquisitionStopFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType AcquisitionStart ();
        VmbErrorType GetAcquisitionStartFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionMode (AcquisitionModeEnum & value);
        VmbErrorType SetAcquisitionMode (AcquisitionModeEnum value);
        VmbErrorType GetAcquisitionModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionFrameCount (VmbInt64_t & value);
        VmbErrorType SetAcquisitionFrameCount (VmbInt64_t value);
        VmbErrorType GetAcquisitionFrameCountFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /AnalogControl
        VmbErrorType GetGain (double & value);
        VmbErrorType SetGain (double value);
        VmbErrorType GetGainFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGainRaw (VmbInt64_t & value);
        VmbErrorType SetGainRaw (VmbInt64_t value);
        VmbErrorType GetGainRawFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /BufferHandlingControl
        VmbErrorType GetStreamAnnounceBufferMinimum (VmbInt64_t & value);
        VmbErrorType GetStreamAnnounceBufferMinimumFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamAnnouncedBufferCount (VmbInt64_t & value);
        VmbErrorType GetStreamAnnouncedBufferCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamBufferHandlingMode (StreamBufferHandlingModeEnum & value);
        VmbErrorType SetStreamBufferHandlingMode (StreamBufferHandlingModeEnum value);
        VmbErrorType GetStreamBufferHandlingModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures
        VmbErrorType AutoCalibrateOnce ();
        VmbErrorType GetAutoCalibrateOnceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAutoCalibrationInterval (VmbInt64_t & value);
        VmbErrorType SetAutoCalibrationInterval (VmbInt64_t value);
        VmbErrorType GetAutoCalibrationIntervalFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAutoCalibrationMode (VmbInt64_t & value);
        VmbErrorType SetAutoCalibrationMode (VmbInt64_t value);
        VmbErrorType GetAutoCalibrationModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCorrectionDataSet (VmbInt64_t & value);
        VmbErrorType SetCorrectionDataSet (VmbInt64_t value);
        VmbErrorType GetCorrectionDataSetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType FlushSerial ();
        VmbErrorType GetFlushSerialFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType ParameterDump ();
        VmbErrorType GetParameterDumpFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType QuerySensorTemperatureState ();
        VmbErrorType GetQuerySensorTemperatureStateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType ReloadCameraSpecialFeatures ();
        VmbErrorType GetReloadCameraSpecialFeaturesFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetSensorTemperatureState (VmbInt64_t & value);
        VmbErrorType GetSensorTemperatureStateFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures/BackgroundCorrection
        VmbErrorType GetBGC_OffsetValue (VmbInt64_t & value);
        VmbErrorType SetBGC_OffsetValue (VmbInt64_t value);
        VmbErrorType GetBGC_OffsetValueFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetBGC_OperationMode (VmbInt64_t & value);
        VmbErrorType SetBGC_OperationMode (VmbInt64_t value);
        VmbErrorType GetBGC_OperationModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures/BadPixelCorrection
        VmbErrorType GetBPC_CorrectionData_FileNumber (VmbInt64_t & value);
        VmbErrorType GetBPC_CorrectionData_FileNumberFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetBPC_OperationMode (BPC_OperationModeEnum & value);
        VmbErrorType SetBPC_OperationMode (BPC_OperationModeEnum value);
        VmbErrorType GetBPC_OperationModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures/IntegratorAndImageStore
        VmbErrorType GetIIS_OperationMode (VmbInt64_t & value);
        VmbErrorType SetIIS_OperationMode (VmbInt64_t value);
        VmbErrorType GetIIS_OperationModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures/LUT
        VmbErrorType GetLUT_CorrectionData_FileNumber (VmbInt64_t & value);
        VmbErrorType GetLUT_CorrectionData_FileNumberFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLUT_OperationMode (LUT_OperationModeEnum & value);
        VmbErrorType SetLUT_OperationMode (LUT_OperationModeEnum value);
        VmbErrorType GetLUT_OperationModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CameraSpecialFeatures/TwoPointCorrection
        VmbErrorType GetTPC_CorrectionData_FileNumber (VmbInt64_t & value);
        VmbErrorType GetTPC_CorrectionData_FileNumberFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTPC_FirstImage_HighRef (VmbInt64_t & value);
        VmbErrorType GetTPC_FirstImage_HighRefFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTPC_FirstImage_LowRef (VmbInt64_t & value);
        VmbErrorType GetTPC_FirstImage_LowRefFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTPC_OperationMode (TPC_OperationModeEnum & value);
        VmbErrorType SetTPC_OperationMode (TPC_OperationModeEnum value);
        VmbErrorType GetTPC_OperationModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTPC_SetValue_HighRef (VmbInt64_t & value);
        VmbErrorType GetTPC_SetValue_HighRefFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTPC_SetValue_LowRef (VmbInt64_t & value);
        VmbErrorType GetTPC_SetValue_LowRefFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CounterAndTimerControl
        VmbErrorType GetCounterDecrementEventSource (CounterDecrementEventSourceEnum & value);
        VmbErrorType SetCounterDecrementEventSource (CounterDecrementEventSourceEnum value);
        VmbErrorType GetCounterDecrementEventSourceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCounterResetActivation (CounterResetActivationEnum & value);
        VmbErrorType SetCounterResetActivation (CounterResetActivationEnum value);
        VmbErrorType GetCounterResetActivationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCounterResetSource (CounterResetSourceEnum & value);
        VmbErrorType SetCounterResetSource (CounterResetSourceEnum value);
        VmbErrorType GetCounterResetSourceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerDelayRaw (VmbInt64_t & value);
        VmbErrorType SetTimerDelayRaw (VmbInt64_t value);
        VmbErrorType GetTimerDelayRawFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerDurationRaw (VmbInt64_t & value);
        VmbErrorType SetTimerDurationRaw (VmbInt64_t value);
        VmbErrorType GetTimerDurationRawFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerGranularityFactor (VmbInt64_t & value);
        VmbErrorType SetTimerGranularityFactor (VmbInt64_t value);
        VmbErrorType GetTimerGranularityFactorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerSelector (TimerSelectorEnum & value);
        VmbErrorType SetTimerSelector (TimerSelectorEnum value);
        VmbErrorType GetTimerSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerTriggerActivation (TimerTriggerActivationEnum & value);
        VmbErrorType SetTimerTriggerActivation (TimerTriggerActivationEnum value);
        VmbErrorType GetTimerTriggerActivationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimerTriggerSource (TimerTriggerSourceEnum & value);
        VmbErrorType SetTimerTriggerSource (TimerTriggerSourceEnum value);
        VmbErrorType GetTimerTriggerSourceFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /DeviceControl
        VmbErrorType GetDeviceID (std::string & value);
        VmbErrorType GetDeviceIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceManufacturerInfo (std::string & value);
        VmbErrorType GetDeviceManufacturerInfoFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceModelName (std::string & value);
        VmbErrorType GetDeviceModelNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceScanType (DeviceScanTypeEnum & value);
        VmbErrorType SetDeviceScanType (DeviceScanTypeEnum value);
        VmbErrorType GetDeviceScanTypeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceUserID (std::string & value);
        VmbErrorType SetDeviceUserID (const char * value);
        VmbErrorType GetDeviceUserIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceVendorName (std::string & value);
        VmbErrorType GetDeviceVendorNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceVersion (std::string & value);
        VmbErrorType GetDeviceVersionFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /EventControl
        VmbErrorType GetEventNotification (EventNotificationEnum & value);
        VmbErrorType SetEventNotification (EventNotificationEnum value);
        VmbErrorType GetEventNotificationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetEventSelector (EventSelectorEnum & value);
        VmbErrorType SetEventSelector (EventSelectorEnum value);
        VmbErrorType GetEventSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /GigE
        VmbErrorType GetGevSCPSPacketSize (VmbInt64_t & value);
        VmbErrorType SetGevSCPSPacketSize (VmbInt64_t value);
        VmbErrorType GetGevSCPSPacketSizeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /GigE/Configuration
        VmbErrorType GetGevIPConfigurationMode (GevIPConfigurationModeEnum & value);
        VmbErrorType GetGevIPConfigurationModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /GigE/Current
        VmbErrorType GetGevCurrentDefaultGateway (VmbInt64_t & value);
        VmbErrorType GetGevCurrentDefaultGatewayFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCurrentIPAddress (VmbInt64_t & value);
        VmbErrorType GetGevCurrentIPAddressFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCurrentSubnetMask (VmbInt64_t & value);
        VmbErrorType GetGevCurrentSubnetMaskFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /GigE/GVCP
        VmbErrorType GetGVCPCmdRetries (VmbInt64_t & value);
        VmbErrorType SetGVCPCmdRetries (VmbInt64_t value);
        VmbErrorType GetGVCPCmdRetriesFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVCPCmdTimeout (VmbInt64_t & value);
        VmbErrorType SetGVCPCmdTimeout (VmbInt64_t value);
        VmbErrorType GetGVCPCmdTimeoutFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevHeartbeatInterval (VmbInt64_t & value);
        VmbErrorType SetGevHeartbeatInterval (VmbInt64_t value);
        VmbErrorType GetGevHeartbeatIntervalFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /GigE/Persistent
        VmbErrorType GetGevPersistentDefaultGateway (VmbInt64_t & value);
        VmbErrorType GetGevPersistentDefaultGatewayFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevPersistentIPAddress (VmbInt64_t & value);
        VmbErrorType GetGevPersistentIPAddressFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevPersistentSubnetMask (VmbInt64_t & value);
        VmbErrorType GetGevPersistentSubnetMaskFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine
        VmbErrorType GetIPEngineDeviceID (VmbInt64_t & value);
        VmbErrorType GetIPEngineDeviceIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineFirmwareVersionMajor (VmbInt64_t & value);
        VmbErrorType GetIPEngineFirmwareVersionMajorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineFirmwareVersionMinor (VmbInt64_t & value);
        VmbErrorType GetIPEngineFirmwareVersionMinorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineFirmwareVersionSubminor (VmbInt64_t & value);
        VmbErrorType GetIPEngineFirmwareVersionSubminorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineInitSequenceStatus (VmbInt64_t & value);
        VmbErrorType GetIPEngineInitSequenceStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineModuleID (VmbInt64_t & value);
        VmbErrorType GetIPEngineModuleIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineSubModuleID (VmbInt64_t & value);
        VmbErrorType GetIPEngineSubModuleIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetIPEngineVendorID (VmbInt64_t & value);
        VmbErrorType GetIPEngineVendorIDFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine/Grabber/Channel0/AcquisitionConfiguration
        VmbErrorType GetGrbCh0AcqCfgIncludeMetadataInImage (bool & value);
        VmbErrorType SetGrbCh0AcqCfgIncludeMetadataInImage (bool value);
        VmbErrorType GetGrbCh0AcqCfgIncludeMetadataInImageFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0AcqCfgInvertPixelData (bool & value);
        VmbErrorType SetGrbCh0AcqCfgInvertPixelData (bool value);
        VmbErrorType GetGrbCh0AcqCfgInvertPixelDataFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0AcqCfgMemoryWaterLevel (GrbCh0AcqCfgMemoryWaterLevelEnum & value);
        VmbErrorType SetGrbCh0AcqCfgMemoryWaterLevel (GrbCh0AcqCfgMemoryWaterLevelEnum value);
        VmbErrorType GetGrbCh0AcqCfgMemoryWaterLevelFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0AcqCfgPixelBusDataPortMapping (GrbCh0AcqCfgPixelBusDataPortMappingEnum & value);
        VmbErrorType SetGrbCh0AcqCfgPixelBusDataPortMapping (GrbCh0AcqCfgPixelBusDataPortMappingEnum value);
        VmbErrorType GetGrbCh0AcqCfgPixelBusDataPortMappingFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine/Grabber/Channel0/TriggerConfiguration
        VmbErrorType GetGrbCh0TrigCfgAutomaticInternalRetrigger (bool & value);
        VmbErrorType SetGrbCh0TrigCfgAutomaticInternalRetrigger (bool value);
        VmbErrorType GetGrbCh0TrigCfgAutomaticInternalRetriggerFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0TrigCfgContinuousPipeCount (GrbCh0TrigCfgContinuousPipeCountEnum & value);
        VmbErrorType SetGrbCh0TrigCfgContinuousPipeCount (GrbCh0TrigCfgContinuousPipeCountEnum value);
        VmbErrorType GetGrbCh0TrigCfgContinuousPipeCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0TrigCfgFrameToSkip (VmbInt64_t & value);
        VmbErrorType SetGrbCh0TrigCfgFrameToSkip (VmbInt64_t value);
        VmbErrorType GetGrbCh0TrigCfgFrameToSkipFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine/Grabber/Channel0Extension/GrabberMetadata
        VmbErrorType GetGrbCh0MetadataInsertionMode (GrbCh0MetadataInsertionModeEnum & value);
        VmbErrorType SetGrbCh0MetadataInsertionMode (GrbCh0MetadataInsertionModeEnum value);
        VmbErrorType GetGrbCh0MetadataInsertionModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0MetadataMsbOverride (GrbCh0MetadataMsbOverrideEnum & value);
        VmbErrorType SetGrbCh0MetadataMsbOverride (GrbCh0MetadataMsbOverrideEnum value);
        VmbErrorType GetGrbCh0MetadataMsbOverrideFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGrbCh0MetadataSourceSelection (GrbCh0MetadataSourceSelectionEnum & value);
        VmbErrorType SetGrbCh0MetadataSourceSelection (GrbCh0MetadataSourceSelectionEnum value);
        VmbErrorType GetGrbCh0MetadataSourceSelectionFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine/PortCommunication/Uart0
        VmbErrorType GetUart0BaudRate (Uart0BaudRateEnum & value);
        VmbErrorType SetUart0BaudRate (Uart0BaudRateEnum value);
        VmbErrorType GetUart0BaudRateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0BaudRateFactor (VmbInt64_t & value);
        VmbErrorType SetUart0BaudRateFactor (VmbInt64_t value);
        VmbErrorType GetUart0BaudRateFactorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0BreakDetection (bool & value);
        VmbErrorType SetUart0BreakDetection (bool value);
        VmbErrorType GetUart0BreakDetectionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0BreakGeneration (bool & value);
        VmbErrorType SetUart0BreakGeneration (bool value);
        VmbErrorType GetUart0BreakGenerationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0Loopback (bool & value);
        VmbErrorType SetUart0Loopback (bool value);
        VmbErrorType GetUart0LoopbackFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0NumOfStopBits (Uart0NumOfStopBitsEnum & value);
        VmbErrorType SetUart0NumOfStopBits (Uart0NumOfStopBitsEnum value);
        VmbErrorType GetUart0NumOfStopBitsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0Parity (Uart0ParityEnum & value);
        VmbErrorType SetUart0Parity (Uart0ParityEnum value);
        VmbErrorType GetUart0ParityFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart0ReadyToReceive (bool & value);
        VmbErrorType SetUart0ReadyToReceive (bool value);
        VmbErrorType GetUart0ReadyToReceiveFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /IPEngine/PortCommunication/Uart1
        VmbErrorType GetUart1BaudRate (Uart1BaudRateEnum & value);
        VmbErrorType SetUart1BaudRate (Uart1BaudRateEnum value);
        VmbErrorType GetUart1BaudRateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1BaudRateFactor (VmbInt64_t & value);
        VmbErrorType SetUart1BaudRateFactor (VmbInt64_t value);
        VmbErrorType GetUart1BaudRateFactorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1BreakDetection (bool & value);
        VmbErrorType SetUart1BreakDetection (bool value);
        VmbErrorType GetUart1BreakDetectionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1BreakGeneration (bool & value);
        VmbErrorType SetUart1BreakGeneration (bool value);
        VmbErrorType GetUart1BreakGenerationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1Loopback (bool & value);
        VmbErrorType SetUart1Loopback (bool value);
        VmbErrorType GetUart1LoopbackFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1NumOfStopBits (Uart1NumOfStopBitsEnum & value);
        VmbErrorType SetUart1NumOfStopBits (Uart1NumOfStopBitsEnum value);
        VmbErrorType GetUart1NumOfStopBitsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1Parity (Uart1ParityEnum & value);
        VmbErrorType SetUart1Parity (Uart1ParityEnum value);
        VmbErrorType GetUart1ParityFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUart1ReadyToReceive (bool & value);
        VmbErrorType SetUart1ReadyToReceive (bool value);
        VmbErrorType GetUart1ReadyToReceiveFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /ImageFormatControl
        VmbErrorType GetDecimationHorizontal (VmbInt64_t & value);
        VmbErrorType SetDecimationHorizontal (VmbInt64_t value);
        VmbErrorType GetDecimationHorizontalFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDecimationVertical (VmbInt64_t & value);
        VmbErrorType SetDecimationVertical (VmbInt64_t value);
        VmbErrorType GetDecimationVerticalFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetHeight (VmbInt64_t & value);
        VmbErrorType SetHeight (VmbInt64_t value);
        VmbErrorType GetHeightFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetHeightMax (VmbInt64_t & value);
        VmbErrorType GetHeightMaxFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOffsetX (VmbInt64_t & value);
        VmbErrorType SetOffsetX (VmbInt64_t value);
        VmbErrorType GetOffsetXFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOffsetY (VmbInt64_t & value);
        VmbErrorType SetOffsetY (VmbInt64_t value);
        VmbErrorType GetOffsetYFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelCoding (PixelCodingEnum & value);
        VmbErrorType GetPixelCodingFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelColorFilter (PixelColorFilterEnum & value);
        VmbErrorType GetPixelColorFilterFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelFormat (PixelFormatEnum & value);
        VmbErrorType GetPixelFormatFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelSize (PixelSizeEnum & value);
        VmbErrorType GetPixelSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetSensorHeight (VmbInt64_t & value);
        VmbErrorType GetSensorHeightFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetSensorWidth (VmbInt64_t & value);
        VmbErrorType GetSensorWidthFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTestImageSelector (TestImageSelectorEnum & value);
        VmbErrorType SetTestImageSelector (TestImageSelectorEnum value);
        VmbErrorType GetTestImageSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetWidth (VmbInt64_t & value);
        VmbErrorType SetWidth (VmbInt64_t value);
        VmbErrorType GetWidthFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetWidthMax (VmbInt64_t & value);
        VmbErrorType GetWidthMaxFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /Info
        VmbErrorType GetGevDeviceMACAddress (VmbInt64_t & value);
        VmbErrorType GetGevDeviceMACAddressFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /Stream/Info
        VmbErrorType GetGVSPFilterVersion (std::string & value);
        VmbErrorType GetGVSPFilterVersionFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /Stream/Multicast
        VmbErrorType GetMulticastEnable (bool & value);
        VmbErrorType SetMulticastEnable (bool value);
        VmbErrorType GetMulticastEnableFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetMulticastIPAddress (VmbInt64_t & value);
        VmbErrorType SetMulticastIPAddress (VmbInt64_t value);
        VmbErrorType GetMulticastIPAddressFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /Stream/Settings
        VmbErrorType GVSPAdjustPacketSize ();
        VmbErrorType GetGVSPAdjustPacketSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPBurstSize (VmbInt64_t & value);
        VmbErrorType SetGVSPBurstSize (VmbInt64_t value);
        VmbErrorType GetGVSPBurstSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPDriver (GVSPDriverEnum & value);
        VmbErrorType SetGVSPDriver (GVSPDriverEnum value);
        VmbErrorType GetGVSPDriverFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPHostReceiveBuffers (VmbInt64_t & value);
        VmbErrorType SetGVSPHostReceiveBuffers (VmbInt64_t value);
        VmbErrorType GetGVSPHostReceiveBuffersFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPMaxLookBack (VmbInt64_t & value);
        VmbErrorType SetGVSPMaxLookBack (VmbInt64_t value);
        VmbErrorType GetGVSPMaxLookBackFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPMaxRequests (VmbInt64_t & value);
        VmbErrorType SetGVSPMaxRequests (VmbInt64_t value);
        VmbErrorType GetGVSPMaxRequestsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPMaxWaitSize (VmbInt64_t & value);
        VmbErrorType SetGVSPMaxWaitSize (VmbInt64_t value);
        VmbErrorType GetGVSPMaxWaitSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPMissingSize (VmbInt64_t & value);
        VmbErrorType SetGVSPMissingSize (VmbInt64_t value);
        VmbErrorType GetGVSPMissingSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPPacketSize (VmbInt64_t & value);
        VmbErrorType SetGVSPPacketSize (VmbInt64_t value);
        VmbErrorType GetGVSPPacketSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPTiltingSize (VmbInt64_t & value);
        VmbErrorType SetGVSPTiltingSize (VmbInt64_t value);
        VmbErrorType GetGVSPTiltingSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGVSPTimeout (VmbInt64_t & value);
        VmbErrorType SetGVSPTimeout (VmbInt64_t value);
        VmbErrorType GetGVSPTimeoutFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /Stream/Statistics
        VmbErrorType GetStatFrameDelivered (VmbInt64_t & value);
        VmbErrorType GetStatFrameDeliveredFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatFrameDropped (VmbInt64_t & value);
        VmbErrorType GetStatFrameDroppedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatFrameRate (double & value);
        VmbErrorType GetStatFrameRateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatFrameRescued (VmbInt64_t & value);
        VmbErrorType GetStatFrameRescuedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatFrameShoved (VmbInt64_t & value);
        VmbErrorType GetStatFrameShovedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatFrameUnderrun (VmbInt64_t & value);
        VmbErrorType GetStatFrameUnderrunFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatLocalRate (double & value);
        VmbErrorType GetStatLocalRateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatPacketErrors (VmbInt64_t & value);
        VmbErrorType GetStatPacketErrorsFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatPacketMissed (VmbInt64_t & value);
        VmbErrorType GetStatPacketMissedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatPacketReceived (VmbInt64_t & value);
        VmbErrorType GetStatPacketReceivedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatPacketRequested (VmbInt64_t & value);
        VmbErrorType GetStatPacketRequestedFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatPacketResent (VmbInt64_t & value);
        VmbErrorType GetStatPacketResentFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStatTimeElapsed (double & value);
        VmbErrorType GetStatTimeElapsedFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /StreamInformation
        VmbErrorType GetStreamID (std::string & value);
        VmbErrorType GetStreamIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamType (StreamTypeEnum & value);
        VmbErrorType GetStreamTypeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /TransportLayerControl
        VmbErrorType GetGevStreamChannelCount (VmbInt64_t & value);
        VmbErrorType GetGevStreamChannelCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevStreamChannelSelector (VmbInt64_t & value);
        VmbErrorType SetGevStreamChannelSelector (VmbInt64_t value);
        VmbErrorType GetGevStreamChannelSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedIPConfigurationDHCP (bool & value);
        VmbErrorType GetGevSupportedIPConfigurationDHCPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedIPConfigurationLLA (bool & value);
        VmbErrorType GetGevSupportedIPConfigurationLLAFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedIPConfigurationPersistentIP (bool & value);
        VmbErrorType GetGevSupportedIPConfigurationPersistentIPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOption (bool & value);
        VmbErrorType GetGevSupportedOptionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionSelector (GevSupportedOptionSelectorEnum & value);
        VmbErrorType SetGevSupportedOptionSelector (GevSupportedOptionSelectorEnum value);
        VmbErrorType GetGevSupportedOptionSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsConcatenation (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsConcatenationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsEVENT (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsEVENTFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsEVENTDATA (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsEVENTDATAFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsPACKETRESEND (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsPACKETRESENDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsSerialNumber (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsSerialNumberFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsUserDefinedName (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsUserDefinedNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSupportedOptionalCommandsWRITEMEM (bool & value);
        VmbErrorType GetGevSupportedOptionalCommandsWRITEMEMFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GevTimestampControlLatch ();
        VmbErrorType GetGevTimestampControlLatchFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GevTimestampControlReset ();
        VmbErrorType GetGevTimestampControlResetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GevTimestampControlSet ();
        VmbErrorType GetGevTimestampControlSetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampCounterSelector (GevTimestampCounterSelectorEnum & value);
        VmbErrorType SetGevTimestampCounterSelector (GevTimestampCounterSelectorEnum value);
        VmbErrorType GetGevTimestampCounterSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampResetActivation (GevTimestampResetActivationEnum & value);
        VmbErrorType SetGevTimestampResetActivation (GevTimestampResetActivationEnum value);
        VmbErrorType GetGevTimestampResetActivationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampResetSource (GevTimestampResetSourceEnum & value);
        VmbErrorType SetGevTimestampResetSource (GevTimestampResetSourceEnum value);
        VmbErrorType GetGevTimestampResetSourceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampSetActivation (GevTimestampSetActivationEnum & value);
        VmbErrorType SetGevTimestampSetActivation (GevTimestampSetActivationEnum value);
        VmbErrorType GetGevTimestampSetActivationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampSetSource (GevTimestampSetSourceEnum & value);
        VmbErrorType SetGevTimestampSetSource (GevTimestampSetSourceEnum value);
        VmbErrorType GetGevTimestampSetSourceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampTickFrequency (VmbInt64_t & value);
        VmbErrorType GetGevTimestampTickFrequencyFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampValue (VmbInt64_t & value);
        VmbErrorType GetGevTimestampValueFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevTimestampValueAtSet (VmbInt64_t & value);
        VmbErrorType SetGevTimestampValueAtSet (VmbInt64_t value);
        VmbErrorType GetGevTimestampValueAtSetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevVersionMajor (VmbInt64_t & value);
        VmbErrorType GetGevVersionMajorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevVersionMinor (VmbInt64_t & value);
        VmbErrorType GetGevVersionMinorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPayloadSize (VmbInt64_t & value);
        VmbErrorType GetPayloadSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCCP (GevCCPEnum & value);
        VmbErrorType SetGevCCP (GevCCPEnum value);
        VmbErrorType GetGevCCPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCurrentIPConfigurationDHCP (bool & value);
        VmbErrorType SetGevCurrentIPConfigurationDHCP (bool value);
        VmbErrorType GetGevCurrentIPConfigurationDHCPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCurrentIPConfigurationLLA (bool & value);
        VmbErrorType SetGevCurrentIPConfigurationLLA (bool value);
        VmbErrorType GetGevCurrentIPConfigurationLLAFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevCurrentIPConfigurationPersistentIP (bool & value);
        VmbErrorType SetGevCurrentIPConfigurationPersistentIP (bool value);
        VmbErrorType GetGevCurrentIPConfigurationPersistentIPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevDeviceClass (GevDeviceClassEnum & value);
        VmbErrorType GetGevDeviceClassFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevDeviceModeCharacterSet (GevDeviceModeCharacterSetEnum & value);
        VmbErrorType GetGevDeviceModeCharacterSetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevDeviceModeIsBigEndian (bool & value);
        VmbErrorType GetGevDeviceModeIsBigEndianFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevFirstURL (std::string & value);
        VmbErrorType GetGevFirstURLFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevHeartbeatTimeout (VmbInt64_t & value);
        VmbErrorType SetGevHeartbeatTimeout (VmbInt64_t value);
        VmbErrorType GetGevHeartbeatTimeoutFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevIPConfigurationStatus (GevIPConfigurationStatusEnum & value);
        VmbErrorType GetGevIPConfigurationStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevInterfaceSelector (VmbInt64_t & value);
        VmbErrorType SetGevInterfaceSelector (VmbInt64_t value);
        VmbErrorType GetGevInterfaceSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMACAddress (VmbInt64_t & value);
        VmbErrorType GetGevMACAddressFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMCDA (VmbInt64_t & value);
        VmbErrorType SetGevMCDA (VmbInt64_t value);
        VmbErrorType GetGevMCDAFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMCPHostPort (VmbInt64_t & value);
        VmbErrorType SetGevMCPHostPort (VmbInt64_t value);
        VmbErrorType GetGevMCPHostPortFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMCRC (VmbInt64_t & value);
        VmbErrorType SetGevMCRC (VmbInt64_t value);
        VmbErrorType GetGevMCRCFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMCSP (VmbInt64_t & value);
        VmbErrorType GetGevMCSPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMCTT (VmbInt64_t & value);
        VmbErrorType SetGevMCTT (VmbInt64_t value);
        VmbErrorType GetGevMCTTFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevMessageChannelCount (VmbInt64_t & value);
        VmbErrorType GetGevMessageChannelCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevNumberOfInterfaces (VmbInt64_t & value);
        VmbErrorType GetGevNumberOfInterfacesFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCDA (VmbInt64_t & value);
        VmbErrorType SetGevSCDA (VmbInt64_t value);
        VmbErrorType GetGevSCDAFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPD (VmbInt64_t & value);
        VmbErrorType SetGevSCPD (VmbInt64_t value);
        VmbErrorType GetGevSCPDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPDirection (GevSCPDirectionEnum & value);
        VmbErrorType GetGevSCPDirectionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPHostPort (VmbInt64_t & value);
        VmbErrorType SetGevSCPHostPort (VmbInt64_t value);
        VmbErrorType GetGevSCPHostPortFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPInterfaceIndex (VmbInt64_t & value);
        VmbErrorType SetGevSCPInterfaceIndex (VmbInt64_t value);
        VmbErrorType GetGevSCPInterfaceIndexFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPSBigEndian (bool & value);
        VmbErrorType SetGevSCPSBigEndian (bool value);
        VmbErrorType GetGevSCPSBigEndianFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPSDoNotFragment (bool & value);
        VmbErrorType SetGevSCPSDoNotFragment (bool value);
        VmbErrorType GetGevSCPSDoNotFragmentFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCPSFireTestPacket (bool & value);
        VmbErrorType SetGevSCPSFireTestPacket (bool value);
        VmbErrorType GetGevSCPSFireTestPacketFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSCSP (VmbInt64_t & value);
        VmbErrorType GetGevSCSPFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGevSecondURL (std::string & value);
        VmbErrorType GetGevSecondURLFeature (AVT::VmbAPI::FeaturePtr & feature);


    private:
        AVT::VmbAPI::FeaturePtr m_TriggerSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerModeFeature;
        AVT::VmbAPI::FeaturePtr m_StartExposureTimerFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTime_MinFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTime_MaxFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTimeGranularityFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTimeAbsMsFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTimeAbsFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTimeFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureModeFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTime_MinFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTime_MaxFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTimeGranularityFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTimeAbsMsFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTimeAbsFeature;
        AVT::VmbAPI::FeaturePtr m_DarkTimeFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStopFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStartFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionModeFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionFrameCountFeature;
        AVT::VmbAPI::FeaturePtr m_GainFeature;
        AVT::VmbAPI::FeaturePtr m_GainRawFeature;
        AVT::VmbAPI::FeaturePtr m_StreamAnnounceBufferMinimumFeature;
        AVT::VmbAPI::FeaturePtr m_StreamAnnouncedBufferCountFeature;
        AVT::VmbAPI::FeaturePtr m_StreamBufferHandlingModeFeature;
        AVT::VmbAPI::FeaturePtr m_AutoCalibrateOnceFeature;
        AVT::VmbAPI::FeaturePtr m_AutoCalibrationIntervalFeature;
        AVT::VmbAPI::FeaturePtr m_AutoCalibrationModeFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionDataSetFeature;
        AVT::VmbAPI::FeaturePtr m_FlushSerialFeature;
        AVT::VmbAPI::FeaturePtr m_ParameterDumpFeature;
        AVT::VmbAPI::FeaturePtr m_QuerySensorTemperatureStateFeature;
        AVT::VmbAPI::FeaturePtr m_ReloadCameraSpecialFeaturesFeature;
        AVT::VmbAPI::FeaturePtr m_SensorTemperatureStateFeature;
        AVT::VmbAPI::FeaturePtr m_BGC_OffsetValueFeature;
        AVT::VmbAPI::FeaturePtr m_BGC_OperationModeFeature;
        AVT::VmbAPI::FeaturePtr m_BPC_CorrectionData_FileNumberFeature;
        AVT::VmbAPI::FeaturePtr m_BPC_OperationModeFeature;
        AVT::VmbAPI::FeaturePtr m_IIS_OperationModeFeature;
        AVT::VmbAPI::FeaturePtr m_LUT_CorrectionData_FileNumberFeature;
        AVT::VmbAPI::FeaturePtr m_LUT_OperationModeFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_CorrectionData_FileNumberFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_FirstImage_HighRefFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_FirstImage_LowRefFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_OperationModeFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_SetValue_HighRefFeature;
        AVT::VmbAPI::FeaturePtr m_TPC_SetValue_LowRefFeature;
        AVT::VmbAPI::FeaturePtr m_CounterDecrementEventSourceFeature;
        AVT::VmbAPI::FeaturePtr m_CounterResetActivationFeature;
        AVT::VmbAPI::FeaturePtr m_CounterResetSourceFeature;
        AVT::VmbAPI::FeaturePtr m_TimerDelayRawFeature;
        AVT::VmbAPI::FeaturePtr m_TimerDurationRawFeature;
        AVT::VmbAPI::FeaturePtr m_TimerGranularityFactorFeature;
        AVT::VmbAPI::FeaturePtr m_TimerSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_TimerTriggerActivationFeature;
        AVT::VmbAPI::FeaturePtr m_TimerTriggerSourceFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceIDFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceManufacturerInfoFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceModelNameFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceScanTypeFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceUserIDFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceVendorNameFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceVersionFeature;
        AVT::VmbAPI::FeaturePtr m_EventNotificationFeature;
        AVT::VmbAPI::FeaturePtr m_EventSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPSPacketSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GevIPConfigurationModeFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentDefaultGatewayFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentIPAddressFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentSubnetMaskFeature;
        AVT::VmbAPI::FeaturePtr m_GVCPCmdRetriesFeature;
        AVT::VmbAPI::FeaturePtr m_GVCPCmdTimeoutFeature;
        AVT::VmbAPI::FeaturePtr m_GevHeartbeatIntervalFeature;
        AVT::VmbAPI::FeaturePtr m_GevPersistentDefaultGatewayFeature;
        AVT::VmbAPI::FeaturePtr m_GevPersistentIPAddressFeature;
        AVT::VmbAPI::FeaturePtr m_GevPersistentSubnetMaskFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineDeviceIDFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineFirmwareVersionMajorFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineFirmwareVersionMinorFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineFirmwareVersionSubminorFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineInitSequenceStatusFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineModuleIDFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineSubModuleIDFeature;
        AVT::VmbAPI::FeaturePtr m_IPEngineVendorIDFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0AcqCfgIncludeMetadataInImageFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0AcqCfgInvertPixelDataFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0AcqCfgMemoryWaterLevelFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0AcqCfgPixelBusDataPortMappingFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0TrigCfgAutomaticInternalRetriggerFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0TrigCfgContinuousPipeCountFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0TrigCfgFrameToSkipFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0MetadataInsertionModeFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0MetadataMsbOverrideFeature;
        AVT::VmbAPI::FeaturePtr m_GrbCh0MetadataSourceSelectionFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0BaudRateFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0BaudRateFactorFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0BreakDetectionFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0BreakGenerationFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0LoopbackFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0NumOfStopBitsFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0ParityFeature;
        AVT::VmbAPI::FeaturePtr m_Uart0ReadyToReceiveFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1BaudRateFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1BaudRateFactorFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1BreakDetectionFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1BreakGenerationFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1LoopbackFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1NumOfStopBitsFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1ParityFeature;
        AVT::VmbAPI::FeaturePtr m_Uart1ReadyToReceiveFeature;
        AVT::VmbAPI::FeaturePtr m_DecimationHorizontalFeature;
        AVT::VmbAPI::FeaturePtr m_DecimationVerticalFeature;
        AVT::VmbAPI::FeaturePtr m_HeightFeature;
        AVT::VmbAPI::FeaturePtr m_HeightMaxFeature;
        AVT::VmbAPI::FeaturePtr m_OffsetXFeature;
        AVT::VmbAPI::FeaturePtr m_OffsetYFeature;
        AVT::VmbAPI::FeaturePtr m_PixelCodingFeature;
        AVT::VmbAPI::FeaturePtr m_PixelColorFilterFeature;
        AVT::VmbAPI::FeaturePtr m_PixelFormatFeature;
        AVT::VmbAPI::FeaturePtr m_PixelSizeFeature;
        AVT::VmbAPI::FeaturePtr m_SensorHeightFeature;
        AVT::VmbAPI::FeaturePtr m_SensorWidthFeature;
        AVT::VmbAPI::FeaturePtr m_TestImageSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_WidthFeature;
        AVT::VmbAPI::FeaturePtr m_WidthMaxFeature;
        AVT::VmbAPI::FeaturePtr m_GevDeviceMACAddressFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPFilterVersionFeature;
        AVT::VmbAPI::FeaturePtr m_MulticastEnableFeature;
        AVT::VmbAPI::FeaturePtr m_MulticastIPAddressFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPAdjustPacketSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPBurstSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPDriverFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPHostReceiveBuffersFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPMaxLookBackFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPMaxRequestsFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPMaxWaitSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPMissingSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPPacketSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPTiltingSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GVSPTimeoutFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameDeliveredFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameDroppedFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameRateFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameRescuedFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameShovedFeature;
        AVT::VmbAPI::FeaturePtr m_StatFrameUnderrunFeature;
        AVT::VmbAPI::FeaturePtr m_StatLocalRateFeature;
        AVT::VmbAPI::FeaturePtr m_StatPacketErrorsFeature;
        AVT::VmbAPI::FeaturePtr m_StatPacketMissedFeature;
        AVT::VmbAPI::FeaturePtr m_StatPacketReceivedFeature;
        AVT::VmbAPI::FeaturePtr m_StatPacketRequestedFeature;
        AVT::VmbAPI::FeaturePtr m_StatPacketResentFeature;
        AVT::VmbAPI::FeaturePtr m_StatTimeElapsedFeature;
        AVT::VmbAPI::FeaturePtr m_StreamIDFeature;
        AVT::VmbAPI::FeaturePtr m_StreamTypeFeature;
        AVT::VmbAPI::FeaturePtr m_GevStreamChannelCountFeature;
        AVT::VmbAPI::FeaturePtr m_GevStreamChannelSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedIPConfigurationDHCPFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedIPConfigurationLLAFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedIPConfigurationPersistentIPFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsConcatenationFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsEVENTFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsEVENTDATAFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsPACKETRESENDFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsSerialNumberFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsUserDefinedNameFeature;
        AVT::VmbAPI::FeaturePtr m_GevSupportedOptionalCommandsWRITEMEMFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampControlLatchFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampControlResetFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampControlSetFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampCounterSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampResetActivationFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampResetSourceFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampSetActivationFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampSetSourceFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampTickFrequencyFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampValueFeature;
        AVT::VmbAPI::FeaturePtr m_GevTimestampValueAtSetFeature;
        AVT::VmbAPI::FeaturePtr m_GevVersionMajorFeature;
        AVT::VmbAPI::FeaturePtr m_GevVersionMinorFeature;
        AVT::VmbAPI::FeaturePtr m_PayloadSizeFeature;
        AVT::VmbAPI::FeaturePtr m_GevCCPFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentIPConfigurationDHCPFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentIPConfigurationLLAFeature;
        AVT::VmbAPI::FeaturePtr m_GevCurrentIPConfigurationPersistentIPFeature;
        AVT::VmbAPI::FeaturePtr m_GevDeviceClassFeature;
        AVT::VmbAPI::FeaturePtr m_GevDeviceModeCharacterSetFeature;
        AVT::VmbAPI::FeaturePtr m_GevDeviceModeIsBigEndianFeature;
        AVT::VmbAPI::FeaturePtr m_GevFirstURLFeature;
        AVT::VmbAPI::FeaturePtr m_GevHeartbeatTimeoutFeature;
        AVT::VmbAPI::FeaturePtr m_GevIPConfigurationStatusFeature;
        AVT::VmbAPI::FeaturePtr m_GevInterfaceSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GevMACAddressFeature;
        AVT::VmbAPI::FeaturePtr m_GevMCDAFeature;
        AVT::VmbAPI::FeaturePtr m_GevMCPHostPortFeature;
        AVT::VmbAPI::FeaturePtr m_GevMCRCFeature;
        AVT::VmbAPI::FeaturePtr m_GevMCSPFeature;
        AVT::VmbAPI::FeaturePtr m_GevMCTTFeature;
        AVT::VmbAPI::FeaturePtr m_GevMessageChannelCountFeature;
        AVT::VmbAPI::FeaturePtr m_GevNumberOfInterfacesFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCDAFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPDFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPDirectionFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPHostPortFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPInterfaceIndexFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPSBigEndianFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPSDoNotFragmentFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCPSFireTestPacketFeature;
        AVT::VmbAPI::FeaturePtr m_GevSCSPFeature;
        AVT::VmbAPI::FeaturePtr m_GevSecondURLFeature;
};

#endif
